development:
  adapter: postgresql
  encoding: unicode
  database: laugh_development
  pool: 5
  username: jono

test:
  adapter: postgresql
  encoding: unicode
  database: laugh_testing
  pool: 5
  username: jono
